name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-22.04
   permissions:
      contents: write
      pull-requests: write
      id-token: write 

   steps:
     - name: checkout repositry 
       uses: actions/checkout@v3
       
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v3
       
     - name: Configure AWS credentials (OIDC)
       uses: aws-actions/configure-aws-credentials@v2
       with:
         role-to-assume: arn:aws:iam::436450225331:role/oidc-assume-role
         aws-region: ap-south-1

     - name: Verify identity
       run: aws sts get-caller-identity
         
     - name: Terraform Init
       run: terraform init  
        
     - name: Terraform destroy
       id: destroy
       run: terraform destroy -auto-approve
